# Generated by Django 3.1.6 on 2021-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentrequests',
            name='requestOne',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentrequests',
            name='requestThree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentrequests',
            name='requestTwo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
