# Generated by Django 3.1.6 on 2021-04-04 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residentrequests', '0002_auto_20210326_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentrequests',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='residentrequests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='residentrequests',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='residentrequests',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
