# Generated by Django 3.1.6 on 2021-04-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleruser',
            name='AccessLevel',
            field=models.CharField(choices=[('NA', 'not applicable'), ('PGY1', 'year 1 resident'), ('PGY2', 'year 2 resident'), ('PGY3', 'year 3 resident'), ('PGY4', 'year 4 resident'), ('PGY5', 'year 5 resident')], max_length=5),
        ),
    ]
