# Generated by Django 3.1.6 on 2021-04-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0002_auto_20210411_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleruser',
            name='ResidentSchedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
