# Generated by Django 3.1.6 on 2021-03-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('StartSchedule', models.DateField()),
                ('EndSchedule', models.DateField()),
                ('DatesSet', models.BooleanField(default=False)),
            ],
        ),
    ]
