# Generated by Django 3.1.6 on 2021-03-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RotationType', models.CharField(max_length=120)),
                ('StartRotation', models.DateField()),
                ('EndRotation', models.DateField()),
                ('MinResident', models.PositiveIntegerField()),
                ('MaxResident', models.PositiveIntegerField()),
                ('ResidentYear', models.CharField(choices=[('0', 'not applicable'), ('1', 'First year'), ('2', 'Second year'), ('3', 'Third year'), ('4', 'Fourth year'), ('5', 'Fifth year')], default='1', max_length=1)),
            ],
        ),
    ]
