# Generated by Django 3.1.6 on 2021-02-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_criteria_residentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='ResidentYear',
            field=models.CharField(choices=[('0', 'not applicable'), ('1', 'First year'), ('2', 'Second year'), ('3', 'Third year'), ('4', 'Fourth year'), ('5', 'Fifth year')], default='1', max_length=1),
        ),
    ]
