# Generated by Django 3.1.6 on 2021-02-28 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_auto_20210227_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='StartRotation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
